package it.almaviva.moova.pis.intelligentinformationassistant.api.assistant.service;

import it.almaviva.moova.pis.intelligentinformationassistant.api.assistant.model.assistant.AgentBlueprint;
import it.almaviva.moova.pis.intelligentinformationassistant.api.assistant.model.assistant.AgentDataSource;
import it.almaviva.moova.pis.intelligentinformationassistant.api.assistant.model.assistant.AgentGenerationMode;
import it.almaviva.moova.pis.intelligentinformationassistant.api.assistant.model.assistant.AgentGenerationPreviewRequest;
import it.almaviva.moova.pis.intelligentinformationassistant.api.assistant.model.assistant.AgentGenerationPreviewResponse;
import it.almaviva.moova.pis.intelligentinformationassistant.api.assistant.model.assistant.AlertReference;
import it.almaviva.moova.pis.intelligentinformationassistant.api.assistant.model.assistant.SuggestionTargetType;
import it.almaviva.moova.pis.intelligentinformationassistant.api.assistant.repository.preview.AlertAgentGenerationPreviewData;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

@ApplicationScoped
public class AgentGenerationPreviewMapper {

    static final String DETERMINISTIC_PREVIEW_WARNING =
            "Read-only preview generated from verified Alert artifacts; no Agent Definition has been created.";
    static final String LLM_VALIDATED_PREVIEW_WARNING =
            "Agent Blueprint preview generated by LLM and validated by backend; no Agent Definition has been created.";
    static final String DSL_DIAGNOSTIC_WARNING =
            "DSL preview is diagnostic and has not been compiled or executed.";
    static final String PERSISTED_LLM_PREVIEW_WARNING =
            "Validated LLM Agent Blueprint preview has been persisted on the Alert.";
    static final String LLM_FALLBACK_PREVIEW_WARNING =
            "LLM Agent Blueprint generation failed or was rejected by backend validation; deterministic verified Alert artifacts were used instead.";

    private static final Set<String> BLUEPRINT_FIELDS = Set.of(
            "agentName",
            "description",
            "triggerType",
            "requiredSources",
            "targetTypes",
            "parameters",
            "stateRequirements",
            "suggestionIntent");

    private final AgentGenerationCapabilityCatalog capabilityCatalog;
    private final AgentPreviewConditionExtractor conditionExtractor;
    private final AgentPreviewNamingHelper namingHelper;
    private final AgentDslPreviewBuilder dslPreviewBuilder;
    private final AgentValidationPlanBuilder validationPlanBuilder;
    private final AgentBlueprintValidator blueprintValidator;
    private final AgentDefinitionDraftBuilder agentDefinitionDraftBuilder;

    public AgentGenerationPreviewMapper() {
        this(new AgentGenerationCapabilityCatalog(), null, null);
    }

    public AgentGenerationPreviewMapper(
            AgentGenerationCapabilityCatalog capabilityCatalog,
            AgentBlueprintValidator blueprintValidator) {
        this(capabilityCatalog, blueprintValidator, null);
    }

    @Inject
    public AgentGenerationPreviewMapper(
            AgentGenerationCapabilityCatalog capabilityCatalog,
            AgentBlueprintValidator blueprintValidator,
            AgentDefinitionDraftBuilder agentDefinitionDraftBuilder) {
        this.capabilityCatalog = capabilityCatalog;
        this.conditionExtractor = new AgentPreviewConditionExtractor();
        this.namingHelper = new AgentPreviewNamingHelper();
        this.dslPreviewBuilder = new AgentDslPreviewBuilder();
        this.validationPlanBuilder = new AgentValidationPlanBuilder();
        this.blueprintValidator = blueprintValidator == null
                ? new AgentBlueprintValidator(capabilityCatalog)
                : blueprintValidator;
        this.agentDefinitionDraftBuilder = agentDefinitionDraftBuilder == null
                ? new AgentDefinitionDraftBuilder(capabilityCatalog)
                : agentDefinitionDraftBuilder;
    }

    public AgentGenerationPreviewResponse toResponse(
            AlertAgentGenerationPreviewData data,
            AgentGenerationPreviewRequest request) {
        return toResponse(data, request, null, List.of());
    }

    public AgentGenerationPreviewResponse toResponse(
            AlertAgentGenerationPreviewData sourceData,
            AgentGenerationPreviewRequest request,
            Map<String, Object> generatedBlueprint,
            List<String> additionalWarnings) {
        AlertAgentGenerationPreviewData data = generatedBlueprint == null
                ? sourceData
                : withBlueprint(sourceData, generatedBlueprint);
        AgentPreviewConditionExtractor.ConditionSummary conditionSummary = conditionExtractor.extract(data);
        System.out.println("[IIA][AGENT_PREVIEW] Extracted preview condition summary alertId=" + data.alertId()
                + ", conditionType=" + conditionSummary.conditionType()
                + ", location=" + conditionSummary.location()
                + ", cancellation=" + conditionSummary.cancellation()
                + ", delay=" + conditionSummary.delay()
                + ", platformChange=" + conditionSummary.platformChange()
                + ", serviceType=" + conditionSummary.serviceType());
        if (!conditionSummary.stopPointIds().isEmpty()) {
            System.out.println("[IIA][AGENT_PREVIEW][LOCATION] alertId=" + data.alertId()
                    + " stopPointIds=" + conditionSummary.stopPointIds());
        }

        List<String> sourceNames = resolveSourceNames(data);
        List<AgentDataSource> requiredSources = sourceNames.stream()
                .map(this::toDataSource)
                .filter(value -> value != null)
                .toList();
        List<String> requiredPermissions = capabilityCatalog.permissionsForSources(sourceNames);
        AgentGenerationMode requestedMode = request == null ? null : request.getPreferredGenerationMode();
        AgentGenerationMode recommendedMode = capabilityCatalog.recommendedDefaultGenerationMode();

        AgentBlueprint blueprint = toBlueprint(data, conditionSummary, requiredSources);
        AgentBlueprintValidationResult validationResult = blueprintValidator.validate(
                data.alertId(),
                data,
                blueprint,
                conditionSummary,
                sourceNames,
                requiredPermissions,
                requestedMode == null ? null : requestedMode.toString(),
                recommendedMode.toString());
        if (!validationResult.valid() || !validationResult.runtimeSupported()) {
            throw new AlertAgentGenerationPreviewRejectedException(
                    AlertAgentGenerationPreviewRejectedException.Reason.INVALID_BLUEPRINT);
        }
        System.out.println("[IIA][AGENT_PREVIEW] Rendering deterministic DSL preview alertId=" + data.alertId());
        AgentDslPreviewBuilder.BuildResult dslResult = dslPreviewBuilder.build(
                data,
                blueprint,
                conditionSummary,
                sourceNames,
                validationResult);
        if (dslResult.partial() || !dslResult.supportedByRuntime()) {
            throw new AlertAgentGenerationPreviewRejectedException(
                    AlertAgentGenerationPreviewRejectedException.Reason.INVALID_BLUEPRINT);
        }
        LinkedHashSet<String> warnings = new LinkedHashSet<>(data.warnings() == null ? List.of() : data.warnings());
        warnings.addAll(additionalWarnings == null ? List.of() : additionalWarnings);
        if (warnings.contains(LLM_VALIDATED_PREVIEW_WARNING)) {
            warnings.remove(DETERMINISTIC_PREVIEW_WARNING);
        } else {
            warnings.add(DETERMINISTIC_PREVIEW_WARNING);
        }
        warnings.add(DSL_DIAGNOSTIC_WARNING);
        if (requestedMode != null && capabilityCatalog.isPreviewOnlyGenerationMode(requestedMode.toString())) {
            System.out.println("[IIA][AGENT_CAPABILITY] Requested generation mode=" + requestedMode
                    + " is preview-only; falling back to " + recommendedMode);
            warnings.add("JAVA_TEMPLATE was requested but is not generated in the read-only preview MVP; DSL preview is returned when possible.");
        }
        if (dslResult.partial()) {
            warnings.add("DSL preview is partial because some condition nodes are not supported by the deterministic renderer.");
        }
        if (!dslResult.supportedByRuntime()) {
            dslResult.unsupportedCapabilities().forEach(capability ->
                    warnings.add("Capability '" + capability + "' is not supported by the current Agent Generation MVP."));
            warnings.add("The preview can be displayed, but the current runtime catalog does not fully support all required capabilities.");
        }

        it.almaviva.moova.pis.intelligentinformationassistant.api.assistant.model.assistant.AgentComplexity complexity =
                capabilityCatalog.defaultMvpComplexity();
        it.almaviva.moova.pis.intelligentinformationassistant.api.assistant.model.assistant.AgentValidationPlan validationPlan =
                included(request == null ? null : request.getIncludeValidationPlan())
                        ? validationPlanBuilder.build(data, conditionSummary)
                        : null;
        List<String> requiredSourceNames = requiredSources.stream().map(String::valueOf).toList();
        AgentDefinitionDraftCandidate draftCandidate = agentDefinitionDraftBuilder.prepare(
                data,
                blueprint,
                recommendedMode,
                complexity,
                requiredSourceNames,
                requiredPermissions,
                validationResult,
                dslResult.preview(),
                validationPlan,
                previewSource(additionalWarnings));
        AgentGenerationPreviewResponse response = new AgentGenerationPreviewResponse()
                .alert(new AlertReference().id(data.alertId()).name(data.name()))
                .canGenerate(true)
                .recommendedGenerationMode(recommendedMode)
                .estimatedComplexity(complexity)
                .requiredSources(requiredSources)
                .requiredPermissions(requiredPermissions)
                .blueprint(draftCandidate.blueprint())
                .warnings(List.copyOf(warnings))
                .rejectedReason(null);

        if (included(request == null ? null : request.getIncludeDslPreview())) {
            response.dslPreview(dslResult.preview());
        }
        if (validationPlan != null) {
            response.validationPlan(validationPlan);
            System.out.println("[IIA][AGENT_PREVIEW] Validation plan generated alertId=" + data.alertId()
                    + ", positiveExamples=" + response.getValidationPlan().getPositiveExamples().size()
                    + ", negativeExamples=" + response.getValidationPlan().getNegativeExamples().size()
                    + ", edgeCases=" + response.getValidationPlan().getEdgeCases().size());
        }
        System.out.println("[IIA][AGENT_PREVIEW] Preview warnings alertId=" + data.alertId()
                + ", warningsCount=" + response.getWarnings().size());
        return response;
    }

    private AgentDefinitionDraftBuilder.PreviewSource previewSource(List<String> warnings) {
        if (warnings != null && warnings.contains(LLM_VALIDATED_PREVIEW_WARNING)) {
            return AgentDefinitionDraftBuilder.PreviewSource.LLM_VALIDATED;
        }
        if (warnings != null && warnings.contains(LLM_FALLBACK_PREVIEW_WARNING)) {
            return AgentDefinitionDraftBuilder.PreviewSource.LLM_FALLBACK;
        }
        return AgentDefinitionDraftBuilder.PreviewSource.DETERMINISTIC;
    }

    private AgentBlueprint toBlueprint(
            AlertAgentGenerationPreviewData data,
            AgentPreviewConditionExtractor.ConditionSummary conditionSummary,
            List<AgentDataSource> requiredSources) {
        Map<String, Object> persisted = data.agentBlueprintPreview();
        Map<String, Object> suggestionIntent = mapValue(persisted.get("suggestionIntent"));
        if (conditionSummary.cancellation()) {
            suggestionIntent.putIfAbsent("type", "INFORM_OPERATOR");
            suggestionIntent.put("category", "JOURNEY_CANCELLATION");
            suggestionIntent.putIfAbsent("candidateOutput", "CANDIDATE_SUGGESTION");
            suggestionIntent.put("operatorAction", "CHECK_PASSENGER_INFORMATION_PROCEDURES");
        } else if (conditionSummary.delay()) {
            suggestionIntent.putIfAbsent("type", "INFORM_OPERATOR");
            suggestionIntent.put("category", "JOURNEY_DELAY");
            suggestionIntent.putIfAbsent("candidateOutput", "CANDIDATE_SUGGESTION");
            suggestionIntent.put("operatorAction", "CHECK_DELAY_AND_PASSENGER_INFORMATION_PROCEDURES");
        } else if (conditionSummary.platformChange()) {
            suggestionIntent.putIfAbsent("type", "INFORM_OPERATOR");
            suggestionIntent.put("category", "PLATFORM_CHANGE");
            suggestionIntent.putIfAbsent("candidateOutput", "CANDIDATE_SUGGESTION");
            suggestionIntent.put("operatorAction", "CHECK_PLATFORM_CHANGE_AND_PASSENGER_INFORMATION_PROCEDURES");
        }
        AgentBlueprint blueprint = new AgentBlueprint()
                .agentName(namingHelper.agentName(data, conditionSummary))
                .description(namingHelper.description(data, conditionSummary))
                .triggerType(toTriggerType(firstString(
                        persisted.get("triggerType"), data.technicalSpecification().get("triggerType"), "EVENT")))
                .requiredSources(requiredSources)
                .targetTypes(resolveTargetTypes(data, persisted))
                .parameters(mapValue(persisted.get("parameters")))
                .stateRequirements(mapValue(persisted.get("stateRequirements")))
                .suggestionIntent(suggestionIntent);

        persisted.forEach((key, value) -> {
            if (!BLUEPRINT_FIELDS.contains(key)) {
                blueprint.putAdditionalProperty(
                        key,
                        "output".equals(key) ? normalizedOutput(value, conditionSummary) : value);
            }
        });
        return blueprint;
    }

    private Map<String, Object> normalizedOutput(
            Object persistedOutput,
            AgentPreviewConditionExtractor.ConditionSummary conditionSummary) {
        Map<String, Object> output = mapValue(persistedOutput);
        if (conditionSummary.platformChange()) {
            output.putIfAbsent("type", "CANDIDATE_SUGGESTION");
            output.putIfAbsent(
                    "reasonTemplate",
                    "Train ${payload.stopPointJourney.stopPointsJourneyDetails[].vehicleJourneyName} "
                            + "received a platform change at ${payload.stopPointJourney.stopPoint.nameLong}.");
            output.putIfAbsent(
                    "operatorAdviceTemplate",
                    "Verify the platform change and update passenger information procedures.");
        }
        return output;
    }

    private AlertAgentGenerationPreviewData withBlueprint(
            AlertAgentGenerationPreviewData data,
            Map<String, Object> generatedBlueprint) {
        return new AlertAgentGenerationPreviewData(
                data.alertId(),
                data.name(),
                data.status(),
                data.verificationStatus(),
                data.enabled(),
                data.deletedAt(),
                data.version(),
                data.prompt(),
                data.verificationSummary(),
                data.rejectedReason(),
                data.verificationConfidence(),
                data.interpreterType(),
                data.inputModel(),
                data.outputModel(),
                data.technicalSpecification(),
                generatedBlueprint,
                data.interpretedEventNames(),
                data.warnings(),
                data.targetTypes());
    }

    private List<SuggestionTargetType> resolveTargetTypes(
            AlertAgentGenerationPreviewData data,
            Map<String, Object> persisted) {
        Object persistedTargets = persisted.get("targetTypes");
        if (persistedTargets instanceof List<?> targets) {
            List<SuggestionTargetType> result = targets.stream()
                    .map(this::stringValue)
                    .map(this::toTargetType)
                    .filter(value -> value != null)
                    .toList();
            return result;
        }
        return data.targetTypes() == null ? List.of() : data.targetTypes();
    }

    private List<String> resolveSourceNames(AlertAgentGenerationPreviewData data) {
        Object persistedSources = data.agentBlueprintPreview().get("requiredSources");
        List<String> result = new ArrayList<>();
        if (persistedSources instanceof List<?> sources) {
            sources.stream()
                    .map(this::stringValue)
                    .filter(value -> value != null && !value.isBlank())
                    .forEach(result::add);
        }
        if (result.isEmpty()) {
            String technicalSource = stringValue(data.technicalSpecification().get("source"));
            if (technicalSource != null && !technicalSource.isBlank()) {
                result.add(technicalSource);
            }
        }
        return result.isEmpty() ? List.of(capabilityCatalog.defaultSource().toString()) : List.copyOf(result);
    }

    private AgentDataSource toDataSource(String source) {
        if (source == null || source.isBlank()) {
            return null;
        }
        try {
            return AgentDataSource.fromString(source);
        } catch (IllegalArgumentException exception) {
            return null;
        }
    }

    private AgentBlueprint.TriggerTypeEnum toTriggerType(String triggerType) {
        try {
            return AgentBlueprint.TriggerTypeEnum.fromString(triggerType);
        } catch (IllegalArgumentException exception) {
            return null;
        }
    }

    private SuggestionTargetType toTargetType(String targetType) {
        try {
            return SuggestionTargetType.fromString(targetType);
        } catch (IllegalArgumentException exception) {
            return null;
        }
    }

    private boolean included(Boolean value) {
        return value == null || value;
    }

    private Map<String, Object> mapValue(Object value) {
        if (!(value instanceof Map<?, ?> map)) {
            return new LinkedHashMap<>();
        }
        Map<String, Object> result = new LinkedHashMap<>();
        map.forEach((key, nestedValue) -> result.put(String.valueOf(key), nestedValue));
        return result;
    }

    private String firstString(Object... values) {
        for (Object value : values) {
            String stringValue = stringValue(value);
            if (stringValue != null && !stringValue.isBlank()) {
                return stringValue;
            }
        }
        return null;
    }

    private String stringValue(Object value) {
        return value == null ? null : String.valueOf(value);
    }

}
