package it.almaviva.moova.pis.intelligentinformationassistant.api.assistant.ai;

public enum ScheduledAlertLocationRelation {
    SERVICE_DATA_API_QUERY_STOP_POINT,
    CURRENT_STOP_POINT_FILTER,
    ORIGIN_FILTER,
    TIMETABLED_ORIGIN_FILTER,
    DESTINATION_FILTER,
    TIMETABLED_DESTINATION_FILTER,
    ROUTE_FILTER,
    TRANSIT_FILTER,
    CANCELLED_CALL_FILTER,
    REPLACEMENT_FILTER,
    REPLACEMENT_SOURCE_START_FILTER,
    REPLACEMENT_SOURCE_END_FILTER,
    EXCLUSION_FILTER,
    UNKNOWN
}
