package it.almaviva.moova.pis.intelligentinformationassistant.api.assistant.ai;

public enum ScheduledAlertLocationRole {
    MONITORED_STOP_POINT,
    FILTER_CURRENT_STOP_POINT,
    FILTER_ORIGIN_STOP_POINT,
    FILTER_TIMETABLED_ORIGIN_STOP_POINT,
    FILTER_DESTINATION_STOP_POINT,
    FILTER_TIMETABLED_DESTINATION_STOP_POINT,
    FILTER_ROUTE_STOP_POINT,
    FILTER_TRANSIT_STOP_POINT,
    FILTER_CANCELLED_CALL_STOP_POINT,
    FILTER_REPLACEMENT_STOP_POINT,
    FILTER_REPLACEMENT_SOURCE_START_STOP_POINT,
    FILTER_REPLACEMENT_SOURCE_END_STOP_POINT,
    EXCLUDED_STOP_POINT,
    UNKNOWN_LOCATION_ROLE
}
